#!/bin/bash
#SBATCH --job-name=cuda_validation_job         # Job name
#SBATCH --ntasks=1                             # Run a single task...
#SBATCH --cpus-per-task=1                      # ...with a single CPU
#SBATCH --mem=2gb                              # Job memory request
#SBATCH --time=01:00:00                        # Time limit hrs:min:sec
#SBATCH --output=cuda_validation_%j.log        # Standard output and error log
#SBATCH --partition=gpu                        # Select the GPU nodes...
#SBATCH --gres=gpu:1                           # ...and a single GPU
 
echo `date`: executing maxwell 2D validation job on host $HOSTNAME with $SLURM_CPUS_ON_NODE cpu cores
echo
cudaDevs=$(echo $CUDA_VISIBLE_DEVICES | sed -e 's/,/ /g')
echo I can see GPU devices $CUDA_VISIBLE_DEVICES
echo

module load compiler/GCC/11.2.0 system/CUDA/11.0.2-GCC-9.3.0 && make &&

./maxwell -x 400 -y 400 -f 1 -n 1000 -p 5 -q 5 -r 10 -s 10 -e 1