#!/bin/bash
#SBATCH --job-name=maxwell_mpi               # Job name
#SBATCH --ntasks=20                          # Number of tasks
#SBATCH --cpus-per-task=1                    # with one core each
#SBATCH --nodes=2                            # Number of nodes
#SBATCH --ntasks-per-node=10                 # How many tasks on each node
#SBATCH --mem-per-cpu=600mb                  # Memory per processor
#SBATCH --time=00:05:00                      # Time limit hrs:min:sec
#SBATCH --output=mpi_regular_%j.log           # Standard output and error log

echo "Running maxwell_mpi validation job on ${SLURM_NTASKS} CPU cores"

module load compiler/GCC/11.2.0 mpi/OpenMPI/4.1.1-GCC-11.2.0 && make &&
mpiexec -n ${SLURM_NTASKS} ./maxwell -x 400 -y 400 -f 1 -n 1000 -e 1