#!/bin/bash
#SBATCH --job-name=maxwell_omp             # Job name
#SBATCH --ntasks=1                         # Run a single task...
#SBATCH --cpus-per-task=8                  # With 8 cpus
#SBATCH --mem=1gb                          # Job memory request
#SBATCH --time=00:05:00                    # Time limit hrs:min:sec
#SBATCH --output=omp_validation_%j.log     # Standard output and error log

echo My working directory is `pwd`
echo Running OMP validation job on host:
echo -e '\t'`hostname` at `date`
echo $SLURM_CPUS_ON_NODE CPU cores available
echo

./maxwell -x 400 -y 400 -f 1 -n 1000 -l 4 -e 1