#!/bin/bash
#BATCH --job-name=maxwell_2D                  # Job name
#SBATCH --ntasks=1                            # Run a single task...
#SBATCH --cpus-per-task=1                     # With one cpu
#SBATCH --mem=2gb                             # Job memory request
#SBATCH --time=00:05:00                       # Time limit hrs:min:sec
#SBATCH --output=original_validation_%j.log   # Standard output and error log

./maxwell -x 400 -y 400 -c -f 1 -n 1000 -e